### ISSUE TITLE
Overflow Padding issue, On selected date

### ISSUE THREAD

**Issue by tailoristic** [ikicodedev/calendar_timeline#16]

**Comment by ikicodedev** [comment]
Can you include an image capture and indicate the device with which the overflow occurs?

**Comment by ikicodedev** [comment]
BY @tailoristic 

const _DayItem({
Key key,
@required this.dayNumber,
@required this.shortName,
@required this.isSelected,
@required this.onTap,
this.dayColor,
this.activeDayColor,
this.activeDayBackgroundColor,
this.available = true,
this.dotsColor,
this.dayNameColor,
}) : super(key: key);

final double height = 80.0; // CHANGED THIS TO 80 YOU CAN EVEN SET IT TO 72-75 because it was overflowing by 2 pixels
